export ICS_BALTIC_DB_HOST=localhost
export ICS_BALTIC_DB_DBNAME=ivs
export ICS_BALTIC_DB_DBUSER=ivs
export ICS_BALTIC_DB_PASSWD=o3NDz95Q
export ICS_BALTIC_SERVER_IP=192.168.88.243
export ICS_BALTIC_FTP_IPADDR=192.168.88.243
export ICS_BALTIC_FTP_LOGIN=ftpuser
export ICS_BALTIC_FTP_PASSWD=o3NDz95Q
